version: "3.9"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    expose:
      - 8989
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DOCKER_DATA}/sonarr/config:/config
      - media_data:/data
    labels:
      - traefik.enable=true
      - "traefik.http.routers.sonarr.rule=Host(`$HOST`)"
      - "traefik.http.routers.sonarr.entryPoints=web,websecure"
      - "traefik.http.routers.sonarr.middlewares=secured-local"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - media_network
      - traefik_network
    deploy:
      resources:
        limits:
          memory: $MEMORY_LIMIT
          cpus: '$CPU_LIMIT'

networks:
  traefik_network:
    external: true
    name: ${DEFAULT_NETWORK}
  media_network:
    external: true
    name: ${MEDIA_NETWORK}

volumes:
  media_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${MEDIA_VOLUME_PATH}'
