version: "3.9"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    restart: unless-stopped
    volumes:
      - $DOCKER_DATA/mealie/data/:/app/data
    expose:
      - 3000
    environment:
      - API_URL=http://mealie-api:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`$FRONT_HOST`)"
      - "traefik.http.routers.mealie.entryPoints=web,websecure"
      - "traefik.http.routers.mealie.middlewares=secured-external"
      - traefik.http.services.mealie.loadbalancer.server.port=3000
    networks:
      - mealie
      - traefik_network

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    restart: unless-stopped
    volumes:
      - $DOCKER_DATA/mealie/data/:/app/data
    expose:
      - 9000
    environment:
      - ALLOW_SIGNUP=false

      - DB_ENGINE=postgres
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_SERVER=mealie_db
      - POSTGRES_PORT=5432

      # Default Recipe Settings
      - RECIPE_PUBLIC=false
      - RECIPE_SHOW_NUTRITION=true
      - RECIPE_SHOW_ASSETS=true
      - RECIPE_LANDSCAPE_VIEW=true
      - RECIPE_DISABLE_COMMENTS=false
      - RECIPE_DISABLE_AMOUNT=false

      - DEFAULT_EMAIL=$SUPERUSER_EMAIL
      - BASE_URL=https://$FRONT_HOST
      - API_DOCS=false
      # =====================================
      - Email Configuration
      - SMTP_HOST=$MAIL_SMTP_SERVER
      - SMTP_PORT=$MAIL_SMTP_PORT
      - SMTP_FROM_NAME=$MAIL_FROM_NAME
      - SMTP_AUTH_STRATEGY=$MAIL_AUTH_STRAT
      - SMTP_FROM_EMAIL=$MAIL_FROM_MAIL
      - SMTP_USER=$MAIL_USER
      - SMTP_PASSWORD=$MAIL_PASSWORD
    networks:
      - mealie

  mealie_db:
    image: postgres:14.0-alpine3.14
    restart: unless-stopped
    volumes:
      - mealie_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - mealie

networks:
  traefik_network:
    external: true
    name: ${DEFAULT_NETWORK}
  mealie:
    external: false

volumes:
  mealie_db:
