version: "3.9"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.3.0
    container_name: mealie
    restart: unless-stopped
    volumes:
      - $DOCKER_DATA/mealie/data/:/app/data
    expose:
      - 9000
    environment:
      - DB_ENGINE=postgres
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_SERVER=mealie_db
      - POSTGRES_PORT=5432

      - BASE_URL=https://$HOST
      - API_DOCS=false

      # Email Configuration
      - SMTP_HOST=$MAIL_SMTP_SERVER
      - SMTP_PORT=$MAIL_SMTP_PORT
      - SMTP_FROM_NAME=$MAIL_FROM_NAME
      - SMTP_AUTH_STRATEGY=$MAIL_AUTH_STRAT
      - SMTP_FROM_EMAIL=$MAIL_FROM_MAIL
      - SMTP_USER=$MAIL_USER
      - SMTP_PASSWORD=$MAIL_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.rule=Host(`$HOST`)"
      - "traefik.http.routers.mealie.entryPoints=web,websecure"
      - "traefik.http.routers.mealie.middlewares=secured-external"
      - traefik.http.services.mealie.loadbalancer.server.port=9000
    depends_on:
      mealie_db:
        condition: service_healthy
    networks:
      - mealie
      - traefik_network

  mealie_db:
    image: postgres:15.0-alpine3.14
    restart: unless-stopped
    volumes:
      - mealie_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mealie

networks:
  traefik_network:
    external: true
    name: ${DEFAULT_NETWORK}
  mealie:
    external: false

volumes:
  mealie_db:
