version: "3.9"
services:
  cyberchef:
    image: mpepping/cyberchef
    restart: unless-stopped
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cyberchef.rule=Host(`$HOST`)"
      - "traefik.http.routers.cyberchef.entryPoints=web,websecure"
      - "traefik.http.routers.cyberchef.middlewares=secured-external"
      - traefik.http.services.cyberchef.loadbalancer.server.port=8000
    deploy:
      resources:
        limits:
          memory: $MEMORY_LIMIT
          cpus: '$CPU_LIMIT'

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK}
