version: "3.9"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.2
    restart: unless-stopped
    user: 1000:1000
    group_add:
      - "107" #render
      - "44" #video
    expose:
      - 8096
    volumes:
      - $DOCKER_DATA/jellyfin/config:/config
      - $DOCKER_CACHE/jellyfin:/cache
      - $DOCKER_MEDIA/jellyfin/movies:/media/movies
      - $DOCKER_MEDIA/jellyfin/shows:/media/shows
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`$HOST`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.entryPoints=web, websecure"
      - "traefik.http.routers.jellyfin.middlewares=secured-external"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-mw"
      - "traefik.http.middlewares.jellyfin-mw.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.http.middlewares.jellyfin-mw.headers.SSLHost=$HOST"
      - "traefik.http.middlewares.jellyfin-mw.headers.SSLForceHost=true"
      - "traefik.http.middlewares.jellyfin-mw.headers.forceSTSHeader=true"

networks:
  default:
    external: true
    name: ${DEFAULT_NETWORK}
