version: "3.9"
services:
  ghost_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASS
    volumes:
      - ghost_db:/var/lib/mysql
    networks:
      - ghost
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    deploy:
      resources:
        limits:
          memory: $MYSQL_MEMORY_LIMIT
          cpus: '$MYSQL_CPU_LIMIT'

  ghost:
    image: ghost:5.2.3-alpine
    restart: always
    expose:
      - 2368
    depends_on:
      - ghost_db
    environment:
      - url=https://$HOST
      - database__client=mysql
      - database__connection__host=ghost_db
      - database__connection__user=root
      - database__connection__password=$MYSQL_PASS
      - database__connection__database=$MYSQL_DB_NAME
      - mail__transport=SMTP
      - mail__options__service=Mailgun
      - mail__options__auth__user=$MAILGUN_AUTH_USER
      - mail__options__auth__pass=$MAILGUN_AUTH_PASS
      - mail__options__port=$MAILGUN_PORT
      - mail__options__secure=true
      - mail__from='$MAIL_FROM_NAME' <$MAIL_FROM_MAIL>
      - logging__path=content/logs
      - tenor__publicReadOnlyApiKey=$TENOR_API_KEY
    volumes:
      - $DOCKER_DATA/ghost/content:/var/lib/ghost/content
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`$HOST`)"
      - "traefik.http.routers.ghost.entryPoints=web, websecure"
      - "traefik.http.routers.ghost.middlewares=secured-local"
      - traefik.http.services.ghost.loadbalancer.server.port=2368
    networks:
      - ghost
      - traefik_network
    deploy:
      resources:
        limits:
          memory: $GHOST_MEMORY_LIMIT
          cpus: '$GHOST_CPU_LIMIT'


networks:
  traefik_network:
    external: true
    name: ${DEFAULT_NETWORK}
  ghost:
    external: false
    
volumes:
  ghost_db:
